/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;

import java.awt.Graphics;
import java.awt.event.KeyEvent;

/**
 *
 * @author Usuario
 */
public class Vista extends javax.swing.JFrame implements Drawable{

    private Pista fondojuego;
    
    /**
     * Creates new form VentanaPrincipal
     * @param fondojuego
     */
    public Vista(Pista fondojuego) {
        initComponents();
        
        this.fondojuego = fondojuego;
        Thread m=new Thread(this.fondojuego);
        m.start();
    }
    
    @Override
    public void paint(Graphics g)
    {
        
        fondojuego.draw(g);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_0)
            System.exit(0);
        fondojuego.handleKey(evt.getKeyCode());
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Pista fondo = new Pista(0, 0, 820, 600);
        Vista vista = new Vista(fondo);
        fondo.setDrawable(vista);
        vista.setSize(820, 600);
        vista.setVisible(true);
    }

    @Override
    public void redraw() {
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
